---
- name: Deploy overskya - same for all 
  hosts: overskya
  vars: 
    deploy_folder: /home/{{ansible_user}}
    project_folder: '/home/{{ansible_user}}/overskya'
    add_server_config: true
    nodejs_version: "4.x"

  roles:
    - name: geerlingguy.nodejs
      become: yes
  tasks: 
    - apt: pkg=git state=present
      become: yes
    - git:
        accept_hostkey: True
        dest: "{{project_folder}}"
        force: yes
        update: yes
        repo: https://github.com/kjartab/overskya

# #Start the server
- name: Start overskya-server
  gather_facts: false
  hosts: overskya-server
  become: yes
  vars: 
    deploy_folder: /home/{{ansible_user}}
    project_folder: '/home/{{ansible_user}}/overskya'
    add_server_config: true
  roles:
    - nginx
    - setup_overskya_server
  tags: 
    - server

    

# start the nodes
- name: Start overskya-node
  gather_facts: false
  hosts: overskya-nodes
  vars: 
    deploy_folder: /home/{{ansible_user}}
    project_folder: '/home/{{ansible_user}}/overskya'
    add_server_config: true
    overskya_server_ip: "178.62.98.218"
    overskya_server_port: 8183
    overskya_websocket_port: 8000
    node_timeout: 1000
  roles:
    - setup_overskya_node