---
- name: Deploy overskya
  hosts: overskya
  become: yes
  vars: 
    deploy_folder: /home/{{ansible_user}}
    project_folder: '/{{ansible_user}}'
    add_server_config: true
  roles:
    - nodejs
    - overskya

# #Start the server
- name: Start overskya-server
  hosts: overskya-server
  become: yes
  vars: 
    deploy_folder: /home/{{ansible_user}}
    project_folder: '/{{ansible_user}}'
    add_server_config: true
  roles:
    - nginx
    - setup_overskya_server
  tags: 
    - restart
    - server

# start the nodes
- name: Start overskya-node
  hosts: overskya-nodes
  vars: 
    deploy_folder: /home/{{ansible_user}}
    project_folder: '/{{ansible_user}}'
    add_server_config: true
    overskya_server_ip: localhost
    overskya_server_port: 8183
    overskya_websocket_port: 8000
    node_timeout: 1000
  roles:
    - setup_overskya_node
  tags: restart