---
- name: Deploy 
  hosts: overskya
  remote_user: ansible
  roles:
    - overskya

# #Start the server
- name: Start overskya-server
  hosts: overskya-servers
  remote_user: ansible
  roles:
    - setup_overskya_server

# start the nodes
- name: Start overskya-node
  hosts: overskya-nodes
  remote_user: ansible
  vars: 
    overskya_server_ip: www.kartan.no
    overskya_server_port: 8183
    node_timeout: 1000
  roles:
    - setup_overskya_node