---
- name: copy nginx config file
  copy: src=nginx.conf dest=/etc/nginx/conf.d/apps/overskya
  sudo: yes

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: npm global install
  npm: name={{item}} path="~/projects/overskya"
  with_items:
    - bower

- name: Install packages based on packages.json
  npm: path="~/projects/overskya"

- name: Install packages based on bower.json
  bower: path="~/projects/overskya"

- name: Check list of Node.js apps running
  command: forever list
  register: forever_list
  changed_when: false

- name: Stop server node if it is running
  command: forever stop ~/projects/overskya/app/os-server.js
  when: "forever_list.stdout.find('/home/ansible/projects/overskya/app/os-server.js') != -1"

- name: Start overskya server
  command: forever start ~/projects/overskya/app/os-server.js --minUptime 10000
  sudo: no
